#!/usr/bin/env node
// Generates examples/tests/suite_10000.far — 10,000 loop-based regression checks.
// Run: node tools/generate_suite_10000.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const out = path.join(root, 'examples', 'tests', 'suite_10000.far');

const BATCH = 500;
const BATCHES = [
  {
    name: 'int_add',
    body: `    a = i
    b = i * 2
    if (a + b != i * 3) { return i }`,
  },
  {
    name: 'int_sub',
    body: `    x = i + 100
    if (x - i != 100) { return i }`,
  },
  {
    name: 'int_mul',
    body: `    if (i * 7 != i * 7) { return i }`,
  },
  {
    name: 'int_div',
    body: `    n = i + 10
    if (n / 3 != n // 3) { return i }`,
  },
  {
    name: 'int_mod',
    body: `  if (i > 0) {
      if ((i * 5) % 5 != 0) { return i }
    }`,
  },
  {
    name: 'ipow',
    body: `  if (i < 20) {
      if (2 ** i != ipow(2, i)) { return i }
    }`,
  },
  {
    name: 'floor_div',
    body: `    n = i + 50
    if (n // 7 != n / 7) { return i }`,
  },
  {
    name: 'bit_and',
    body: `    if ((i & 255) != (i % 256)) { return i }`,
  },
  {
    name: 'bit_or',
    body: `    if ((i | 0) != i) { return i }`,
  },
  {
    name: 'bit_xor',
    body: `    if ((i ^ i) != 0) { return i }`,
  },
  {
    name: 'shifts',
    body: `  if (i < 16) {
      if ((1 << i) != ipow(2, i)) { return i }
    }`,
  },
  {
    name: 'casts_i32',
    body: `    if (i32(i) != i) { return i }`,
  },
  {
    name: 'casts_u8',
    body: `    v = u8(i)
    if (i32(v) != i % 256) { return i }`,
  },
  {
    name: 'bool_logic',
    body: `  if (i == 0) {
      if (bool(0)) { return i }
    } else {
      if (!bool(1)) { return i }
    }`,
  },
  {
    name: 'float_round',
    body: `    f = f64(i) + 0.49
    if (int(f) != i) { return i }`,
  },
  {
    name: 'math_imin',
    body: `    if (imin(i, i + 1) != i) { return i }`,
  },
  {
    name: 'math_imax',
    body: `    if (imax(i, i + 1) != i + 1) { return i }`,
  },
  {
    name: 'stringify_parse',
    body: `    s = stringify_i64(i)
    if (int(s) != i) { return i }`,
  },
  {
    name: 'hash_fnv',
    body: `    s = stringify_i64(i)
    if (fnv(s) == 0) { return i }`,
  },
  {
    name: 'vec2_add',
    body: `    a = dvec2(f64(i), f64(i + 1))
    b = dvec2(1.0, 1.0)
    c = a + b
    if (int(c.x) != i + 1) { return i }`,
  },
];

const total = BATCH * BATCHES.length;
if (total !== 10000) {
  console.error(`Expected 10000 tests, got ${total}`);
  process.exit(1);
}

const lines = [];
lines.push('# suite_10000.far — AUTO-GENERATED by tools/generate_suite_10000.mjs');
lines.push(`# ${total} assertions in ${BATCHES.length} batches x ${BATCH} iterations`);
lines.push('# Regenerate: node tools/generate_suite_10000.mjs');
lines.push('');
lines.push('import std.hash { fnv }');
lines.push('import std.json { stringify_i64 }');
lines.push('');
lines.push(`def BATCH_SIZE() -> i64 { return ${BATCH} }`);
lines.push('');
lines.push('def run_batch(batch_id: i64, fail_idx: i64) -> i64 {');
lines.push('  if (fail_idx >= 0) {');
lines.push('    n = batch_id * BATCH_SIZE() + fail_idx + 1');
lines.push('    print(n)');
lines.push('    return n');
lines.push('  }');
lines.push('  return 0');
lines.push('}');
lines.push('');

BATCHES.forEach((b, idx) => {
  lines.push(`def batch_${b.name}() -> i64 {`);
  lines.push('  i = 0');
  lines.push(`  while (i < BATCH_SIZE()) {`);
  lines.push(b.body);
  lines.push('    i = i + 1');
  lines.push('  }');
  lines.push('  return -1');
  lines.push('}');
  lines.push('');
});

lines.push('def main() -> i64 {');
BATCHES.forEach((b, idx) => {
  lines.push(`  r = run_batch(${idx}, batch_${b.name}())`);
  lines.push('  if (r != 0) { return r }');
});
lines.push(`  print(${total})`);
lines.push('  return 0');
lines.push('}');
lines.push('');

fs.writeFileSync(out, lines.join('\n'), 'utf8');
console.log(`Wrote ${out} (${total} tests, ${lines.length} lines)`);
